version: '2'

services:
  nginx: 
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    ports:
      - "8000:80"
  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    expose:
      - '3000'
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile-dev
    restart: "always"
    expose:
      - '8080'
    environment:
      - DB_USER=socialapp
      - DB_PASSWORD=socialapp1
      - DB_NAME=social-app
      - JWT_SECRET=myawesomesecretyouknow
    volumes:
      - /app/node_modules
      - ./api:/app
